In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn 
from sklearn import datasets

In [85]:
data = datasets.load_boston()
print("INFORMATION OF DATA\n")
print(data.keys())
print(37*"--")
print("Features:\n",data.data)
print(37*"--")
print("Label:\n",data.target[10:24])
print(37*"--")
print("Target Name:\n",data.feature_names)

INFORMATION OF DATA

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
--------------------------------------------------------------------------
Features:
 [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
--------------------------------------------------------------------------
Label:
 [15.  18.9 21.7 20.4 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5]
--------------------------------------------------------------------------
Target Name:
 ['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [86]:
print(data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [87]:
x_df = pd.DataFrame(data.data, columns=data.feature_names)
y_df = pd.DataFrame(data.target)
print(x_df.shape)
print(y_df.shape)
x_df[:10]

(506, 13)
(506, 1)


CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  
5     18.7  394.12   5.21  
6     15.2  395.60  12.43  
7     15.2  396.90  19.15  
8     15.2  386.63  29.93  
9     15.2  386.71  17.10

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(np.array(x_df), np.array(y_df), random_state = 0)

print(10*"-"+"TRAIN DATA"+10*"-"+"\n")
print("Shape'X' :",X_train.shape)
print("Shape'Y' :",y_train.shape)
print()
print(10*"-"+"TEST DATA"+10*"-"+"\n")
print("Shape'X' :",X_test.shape)
print("Shape'Y' :",y_test.shape)

----------TRAIN DATA----------

Shape'X' : (379, 13)
Shape'Y' : (379, 1)

----------TEST DATA----------

Shape'X' : (127, 13)
Shape'Y' : (127, 1)


In [99]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
print(lr)
lr.fit(X_train, y_train)
print(lr.score(X_train, y_train))
print(lr.score(X_test, y_test))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)
0.7697699488741149
0.6354638433202114


In [100]:
from sklearn.linear_model import Ridge


R = Ridge(alpha=10)
print(R)
R.fit(X_train, y_train)
print(R.score(X_train, y_train))
print(R.score(X_test, y_test))

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)
0.7623745182677772
0.613277304720699


In [101]:
from sklearn.linear_model import Lasso

L = Lasso()
print(L)
L.fit(X_train, y_train)
print(L.score(X_train, y_train))
print(L.score(X_test, y_test))

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)
0.7150499874336981
0.5516247059049908
